branches:
  only:
  - master
language: python
python:
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install coverage python-coveralls
script: coverage run --source=. manage.py test tests
after_success:
  - coveralls
